---
# Note: Semantic Router uses pre-built image from ghcr.io/vllm-project/semantic-router/extproc:latest
# No ImageStream needed for semantic-router
---
# ImageStream for LLM Katan
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: llm-katan
  namespace: vllm-semantic-router
  labels:
    app: llm-katan
    app.kubernetes.io/name: vllm-semantic-router
    app.kubernetes.io/component: model
spec:
  lookupPolicy:
    local: true
